apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ../../addons/container-insights

images:
  - name: smartdoc/gateway
    newName: REPLACE_ME_ECR_REGISTRY/smartdoc-gateway
    newTag: latest
  - name: smartdoc/document
    newName: REPLACE_ME_ECR_REGISTRY/smartdoc-document
    newTag: latest
  - name: smartdoc/analysis
    newName: REPLACE_ME_ECR_REGISTRY/smartdoc-analysis
    newTag: latest
  - name: smartdoc/notification
    newName: REPLACE_ME_ECR_REGISTRY/smartdoc-notification
    newTag: latest

patches:
  - path: patch-configmap-aws.yaml
  - path: patch-pullpolicy.yaml
  - path: patch-ingress-nginx.yaml
