apiVersion: v1
kind: ConfigMap
metadata:
  name: smartdoc-app-config
  namespace: smartdoc
data:
  SPRING_PROFILES_ACTIVE: local
  JAVA_TOOL_OPTIONS: "-XX:+UseContainerSupport -XX:MaxRAMPercentage=75"
  SMARTDOC_DOCUMENT_BASE_URL: http://smartdoc-document:8081
