apiVersion: v1
kind: ConfigMap
metadata:
  name: smartdoc-app-config
  namespace: smartdoc
data:
  SPRING_PROFILES_ACTIVE: local
  JAVA_TOOL_OPTIONS: "-Xms128m -Xmx384m"
  SMARTDOC_DOCUMENT_BASE_URL: http://smartdoc-document:8081
  SMARTDOC_ANALYSIS_BASE_URL: http://smartdoc-analysis:8082
  SMARTDOC_NOTIFICATION_BASE_URL: http://smartdoc-notification:8083
  SMARTDOC_DOCUMENT_CONNECT_TIMEOUT_MS: "1000"
  SMARTDOC_DOCUMENT_READ_TIMEOUT_MS: "2000"
  SMARTDOC_NOTIFICATION_CONNECT_TIMEOUT_MS: "1000"
  SMARTDOC_NOTIFICATION_READ_TIMEOUT_MS: "2000"
  SMARTDOC_LOCAL_UPLOAD_DIR: .smartdoc/uploads
  SMARTDOC_UPSTREAM_CONNECT_TIMEOUT_MS: "1000"
  SMARTDOC_UPSTREAM_READ_TIMEOUT_MS: "3000"
  SMARTDOC_AUTH_ACCESS_TOKEN_TTL_SECONDS: "86400"
  SMARTDOC_AUTH_DEV_EMAIL: test@smartdoc.local
  SMARTDOC_AUTH_DEV_DISPLAY_NAME: SmartDoc Tester
