apiVersion: v1
kind: Service
metadata:
  name: smartdoc-document
  namespace: smartdoc
spec:
  selector:
    app: smartdoc-document
  ports:
    - name: http
      port: 8081
      targetPort: 8081
  type: ClusterIP
